trigger:
  branches:
    include:
      - main

pr: none

parameters:
  - name: BuildConfiguration
    displayName: 'Build Configuration'
    type: string
    default: 'Prod'
    values:
      - 'Dev'
      - 'Prod'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
    - template: build-stage.yml
      parameters:
        BuildConfiguration: ${{ parameters.BuildConfiguration }}

- stage: Deploy
  displayName: 'Deploy stage'
  jobs:
    - template: deploy-stage.yml
      parameters:
        IacScriptPath: '$(Agent.BuildDirectory)/drop/deployment/iac.sh'
        BuildConfiguration: ${{ parameters.BuildConfiguration }}
